version: "3.7"

networks:
  web:
    external: true

services:
  rocketchat:
    container_name: rocketchat
    image: rocketchat/rocket.chat:latest
    restart: always
    environment:
      MONGO_URL: "mongodb://rocketchat-mongodb:27017/rocketchat?replicaSet=rs0&directConnection=true"
      MONGO_OPLOG_URL: "mongodb://rocketchat-mongodb:27017/local?replSet=rs01&directConnection=true"
      ROOT_URL: https://chat.tschannerl.com
      PORT: 3000
    volumes:
      - ./uploads:/app/uploads
    depends_on:
      - rocketchat-mongodb
    networks:
      - web
    labels:
      traefik.enable: true
      traefik.http.routers.rocketchat.entrypoints: http
      traefik.http.routers.rocketchat.rule: Host(`chat.tschannerl.com`)
      traefik.http.middlewares.rocketchat-https-redirect.redirectscheme.scheme: https
      traefik.http.middlewares.rocketchat-https-redirect.redirectscheme.port: 443
      traefik.http.routers.rocketchat.middlewares: rocketchat-https-redirect
      traefik.http.routers.rocketchat-secure.entrypoints: https,https2
      traefik.http.routers.rocketchat-secure.rule: Host(`chat.tschannerl.com`)
      traefik.http.routers.rocketchat-secure.tls: true
      traefik.http.routers.rocketchat-secure.tls.certresolver: mytlschallenge
      traefik.http.routers.rocketchat-secure.service: rocketchat
      traefik.http.services.rocketchat.loadbalancer.server.port: 3000
      traefik.docker.network: web
      com.centurylinklabs.watchtower.scope: autoupdate

  rocketchat-mongodb:
    container_name: rocketchat-mongodb
    hostname: rocketchat-mongodb
    image: mongo:7.0
    restart: always
    command: ["mongod", "--replSet", "rs0", "--bind_ip_all", "--oplogSize", "128"]
    healthcheck:
      test: echo 'rs.initiate()' | mongosh --quiet || exit 1
      interval: 10s
      retries: 5
    volumes:
      - ./data/rocketchat/mongo/data:/data/db
      - ./data/rocketchat/mongo/dump:/dump
      - ./data/rocketchat/mongo/configdb:/data/configdb
    labels:
      traefik.enable: false
      com.centurylinklabs.watchtower.scope: autoupdate
    networks:
      - web

