version: "3.7"

networks:
  web:
    external: true

services:
  rocketchat:
    container_name: rocketchat
    image: rocketchat/rocket.chat:latest
    restart: always
    environment:
      MONGO_URL: "mongodb://rocketchat-mongodb:27017/rocketchat?replicaSet=rs0&directConnection=true"
      MONGO_OPLOG_URL: "mongodb://rocketchat-mongodb:27017/local?replSet=rs01&directConnection=true"
      ROOT_URL: https://chat.tschannerl.com
      PORT: 3000
    volumes:
      - ./uploads:/app/uploads
    depends_on:
      - rocketchat-mongodb
    networks:
      - web
    labels:
      traefik.enable: true
      traefik.http.routers.rocketchat.entrypoints: http
      traefik.http.routers.rocketchat.rule: Host(`chat.tschannerl.com`)
      traefik.http.middlewares.rocketchat-https-redirect.redirectscheme.scheme: https
      traefik.http.middlewares.rocketchat-https-redirect.redirectscheme.port: 443
      traefik.http.routers.rocketchat.middlewares: rocketchat-https-redirect
      traefik.http.routers.rocketchat-secure.entrypoints: https,https2
      traefik.http.routers.rocketchat-secure.rule: Host(`chat.tschannerl.com`)
      traefik.http.routers.rocketchat-secure.tls: true
      traefik.http.routers.rocketchat-secure.tls.certresolver: mytlschallenge
      traefik.http.routers.rocketchat-secure.service: rocketchat
      traefik.http.services.rocketchat.loadbalancer.server.port: 3000
      traefik.docker.network: web
      com.centurylinklabs.watchtower.scope: autoupdate

  rocketchat-mongodb:
    container_name: rocketchat-mongodb
    image: mongo:5.0
    command: mongod --oplogSize 128 --replSet rs0
    restart: always
    volumes:
      - ./data/rocketchat/mongo/data:/data/db
      - ./data/rocketchat/mongo/dump:/dump
      - ./data/rocketchat/mongo/configdb:/data/configdb
    labels:
      traefik.enable: false
      com.centurylinklabs.watchtower.scope: autoupdate
    networks:
      - web

  rocketchat-mongo-init-replica:
    container_name: rocketchat-mongo-init-replica
    image: mongo:4.4
    command: 'bash -c "for i in `seq 1 30`; do mongo rocketchat-mongodb/rocketchat --eval \"rs.initiate({ _id: ''rs0'', members: [ { _id: 0, host: ''localhost:27017'' } ]})\" && s=$$? && break || s=$$?; echo \"Tried $$i times. Waiting 5 secs...\"; sleep 5; done; (exit $$s)"'
    depends_on:
      - rocketchat-mongodb
    networks:
      - web
    volumes:
      - ./data/rocketchat/mongoinit/data:/data/db
      - ./data/rocketchat/mongoinit/configdb:/data/configdb
    labels:
      com.centurylinklabs.watchtower.scope: autoupdate
